apiVersion: numaflow.numaproj.io/v1alpha1
kind: InterStepBufferService
metadata:
  name: default-isb
  namespace: default
spec:
  jetstream:
    version: latest
    persistence:
      volumeSize: 10Gi